#!/usr/bin/env python3
"""Build a manuscript PDF from DOCX and insert vector PDF figures.

Word marker paragraphs:
    [[SECTION_BREAK]]
    [[PDF_FIGURE: Figure_1]]
    [[PDF_FIGURE: Figure_S1; pages=1-3]]

Defaults:
    A4, 25.4 mm margins, Arial 11 pt, 1.5 line spacing,
    continuous line numbers, left-aligned 12 pt title.

Requirements:
    python -m pip install lxml pypdf
    pandoc and xelatex on PATH
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from lxml import etree
from pypdf import PdfReader
from pypdf.generic import ContentStream

SCRIPT_VERSION = "2026-07-21-v2"

PT_PER_MM = 72.0 / 25.4
PAPER_SIZES_PT = {
    "a4": (210.0 * PT_PER_MM, 297.0 * PT_PER_MM),
    "letter": (8.5 * 72.0, 11.0 * 72.0),
}
FIGURE_MARGIN_MM = 10.0
FIGURE_SIDE_MARGIN_MM = 10.0
FIGURE_TOP_MARGIN_MM = 10.0
FIGURE_BOTTOM_MARGIN_MM = 25.4
FIGURE_FOOTSKIP_MM = 10.0

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
NS = {"w": W_NS}

FIGURE_RE = re.compile(
    r"^\s*\[\[\s*PDF_FIGURE\s*:\s*(?P<name>[^;\]]+?)"
    r"(?:\s*;\s*pages\s*=\s*(?P<pages>[^\]]+?))?\s*\]\]\s*$",
    re.IGNORECASE,
)
SECTION_RE = re.compile(r"^\s*\[\[\s*SECTION_BREAK\s*\]\]\s*$", re.IGNORECASE)
INTERNAL_SECTION_RE = re.compile(
    r"^\s*\[\[\s*DOCX_SECTION\s*:\s*(?P<kind>[A-Za-z]+)\s*\]\]\s*$",
    re.IGNORECASE,
)
BLANK_RE = re.compile(r"^\s*\[\[\s*DOCX_BLANK\s*\]\]\s*$", re.IGNORECASE)

BLANK_MARKER = "[[DOCX_BLANK]]"

NO_PARAGRAPH_SPACING_SECTION_TITLES = {
    "reference",
    "references",
    "figure",
    "figures",
    "figure legend",
    "figure legends",
    "figure caption",
    "figure captions",
    "supplementary figure",
    "supplementary figures",
    "supplementary figure legend",
    "supplementary figure legends",
    "supplementary information",
    "supplemental figure",
    "supplemental figures",
    "supplemental figure legend",
    "supplemental figure legends",
    "extended data figure",
    "extended data figures",
}


NO_PARAGRAPH_SPACING_SECTION_PREFIXES = (
    "figure ",
    "supplementary figure ",
    "supplemental figure ",
    "extended data figure ",
)

FIGURE_LEGEND_START_RE = re.compile(
    r"^\s*"
    r"(?:(?:supplementary|supplemental)\s+|extended\s+data\s+)?"
    r"figure\s+"
    r"(?:s\s*)?\d+"
    r"\s*[.:]",
    flags=re.IGNORECASE,
)
SUPERSCRIPT_REPLACEMENTS = {
    "⁰": "0",
    "¹": "1",
    "²": "2",
    "³": "3",
    "⁴": "4",
    "⁵": "5",
    "⁶": "6",
    "⁷": "7",
    "⁸": "8",
    "⁹": "9",
    "⁺": "+",
    "⁻": "-",
    "⁼": "=",
    "⁽": "(",
    "⁾": ")",
    "ⁱ": "i",
    "ⁿ": "n",
}

SUBSCRIPT_REPLACEMENTS = {
    "₀": "0",
    "₁": "1",
    "₂": "2",
    "₃": "3",
    "₄": "4",
    "₅": "5",
    "₆": "6",
    "₇": "7",
    "₈": "8",
    "₉": "9",
    "₊": "+",
    "₋": "-",
    "₌": "=",
    "₍": "(",
    "₎": ")",
    "ₐ": "a",
    "ₑ": "e",
    "ₒ": "o",
    "ₓ": "x",
    "ₕ": "h",
    "ₖ": "k",
    "ₗ": "l",
    "ₘ": "m",
    "ₙ": "n",
    "ₚ": "p",
    "ₛ": "s",
    "ₜ": "t",
}

SUPERSCRIPT_TRANSLATION = str.maketrans(
    SUPERSCRIPT_REPLACEMENTS
)

SUBSCRIPT_TRANSLATION = str.maketrans(
    SUBSCRIPT_REPLACEMENTS
)

SUPERSCRIPT_CHARACTERS = "".join(
    SUPERSCRIPT_REPLACEMENTS
)

SUBSCRIPT_CHARACTERS = "".join(
    SUBSCRIPT_REPLACEMENTS
)

def normalize_unicode_scripts_in_latex(
    latex_text: str,
) -> str:
    """
    Replace Unicode superscript and subscript glyphs with ordinary
    characters inside LaTeX script commands.

    This avoids missing-glyph squares when Arial does not contain a specific
    Unicode superscript or subscript character.

    Examples:
        10⁻³  ->  10\\textsuperscript{-3}
        g₂    ->  g\\textsubscript{2}

    Pandoc-generated constructs such as:

        \\textsuperscript{−3}

    are also normalized to use an ordinary ASCII minus.
    """

    # Clean scripts already generated by Pandoc from Word formatting.
    existing_script_re = re.compile(
        r"\\text(?P<kind>superscript|subscript)"
        r"\{(?P<content>[^{}]*)\}"
    )

    def clean_existing_script(
        match: re.Match[str],
    ) -> str:
        kind = match.group("kind")
        content = match.group("content")

        # Word commonly uses the mathematical Unicode minus U+2212.
        content = content.replace("−", "-")

        if kind == "superscript":
            content = content.translate(
                SUPERSCRIPT_TRANSLATION
            )
        else:
            content = content.translate(
                SUBSCRIPT_TRANSLATION
            )

        return (
            f"\\text{kind}"
            f"{{{content}}}"
        )

    latex_text = existing_script_re.sub(
        clean_existing_script,
        latex_text,
    )

    # Convert literal Unicode superscript sequences such as ⁻³.
    superscript_re = re.compile(
        f"[{re.escape(SUPERSCRIPT_CHARACTERS)}]+"
    )

    latex_text = superscript_re.sub(
        lambda match: (
            "\\textsuperscript{"
            + match.group(0).translate(
                SUPERSCRIPT_TRANSLATION
            )
            + "}"
        ),
        latex_text,
    )

    # Convert literal Unicode subscript sequences such as ₂.
    subscript_re = re.compile(
        f"[{re.escape(SUBSCRIPT_CHARACTERS)}]+"
    )

    latex_text = subscript_re.sub(
        lambda match: (
            "\\textsubscript{"
            + match.group(0).translate(
                SUBSCRIPT_TRANSLATION
            )
            + "}"
        ),
        latex_text,
    )

    return latex_text

def is_figure_legend_start(
    text: str | None,
) -> bool:
    """
    Recognize the first paragraph of a figure legend, including captions
    stored as ordinary Word paragraphs rather than Word headings.
    """
    if text is None:
        return False

    return (
        FIGURE_LEGEND_START_RE.match(
            norm(text)
        )
        is not None
    )


def section_disables_paragraph_spacing(
    heading_text: str,
) -> bool:
    """
    Disable paragraph spacing in References and in ordinary,
    supplementary, supplemental, and extended-data figure sections.

    This also recognizes individual headings such as:
        Figure 1
        Figure S1
        Supplementary Figure S1
        Supplemental Figure S1
        Extended Data Figure 1
    """
    normalized = (
        norm(heading_text)
        .casefold()
        .rstrip(":")
        .strip()
    )

    if normalized in NO_PARAGRAPH_SPACING_SECTION_TITLES:
        return True

    return normalized.startswith(
        NO_PARAGRAPH_SPACING_SECTION_PREFIXES
    )


def header_level_and_text(
    block: dict[str, Any],
) -> tuple[int, str] | None:
    """
    Return the level and normalized text of a Pandoc Header block.
    """
    if block.get("t") != "Header":
        return None

    content = block.get("c")

    if (
        not isinstance(content, list)
        or len(content) < 3
        or not isinstance(content[0], int)
        or not isinstance(content[2], list)
    ):
        return None

    level = content[0]
    text = norm(inline_text(content[2]))

    return level, text


def uses_selective_paragraph_spacing(
    heading_text: str,
) -> bool:
    """
    Return True for manuscript sections that require 12 pt paragraph
    spacing.
    """
    normalized = norm(heading_text).casefold().rstrip(":")

    return normalized in PARAGRAPH_SPACING_SECTION_TITLES

@dataclass(frozen=True)
class Figure:
    key: str
    source: Path
    safe_name: str
    page_count: int


@dataclass(frozen=True)
class Insertion:
    raw_marker: str
    figure: Figure
    pages: tuple[int, ...]


def qn(name: str) -> str:
    return f"{{{W_NS}}}{name}"


def norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def require_program(name: str) -> str:
    path = shutil.which(name)
    if not path:
        raise RuntimeError(f"Required executable not found on PATH: {name}")
    return path


def run(command: list[str], cwd: Path | None = None, capture: bool = False) -> str:
    result = subprocess.run(
        command,
        cwd=cwd,
        check=True,
        text=True,
        encoding="utf-8",
        stdout=subprocess.PIPE if capture else None,
    )
    return result.stdout if capture else ""


def paragraph_text(paragraph: etree._Element) -> str:
    return "".join(paragraph.xpath(".//w:t/text()", namespaces=NS))


def has_nontext_content(paragraph: etree._Element) -> bool:
    """Return True for content that must not be replaced as a blank line."""
    if paragraph.xpath(
        ".//w:drawing | .//w:pict | .//w:object | .//w:sym | "
        ".//w:fldSimple | .//w:instrText",
        namespaces=NS,
    ):
        return True

    # A page or column break is structural. An ordinary line break inside an
    # otherwise empty paragraph still represents visible vertical space.
    return bool(
        paragraph.xpath(
            ".//w:br[@w:type='page' or @w:type='column']",
            namespaces=NS,
        )
    )


def rewrite_paragraph(paragraph: etree._Element, text: str) -> None:
    """Replace paragraph content with one Normal-style text run."""
    p_pr = paragraph.find(qn("pPr"))
    if p_pr is None:
        p_pr = etree.Element(qn("pPr"))
        paragraph.insert(0, p_pr)

    for child in list(paragraph):
        if child is not p_pr:
            paragraph.remove(child)

    p_style = p_pr.find(qn("pStyle"))
    if p_style is None:
        p_style = etree.Element(qn("pStyle"))
        p_pr.insert(0, p_style)
    p_style.set(qn("val"), "Normal")

    run_node = etree.SubElement(paragraph, qn("r"))
    text_node = etree.SubElement(run_node, qn("t"))
    text_node.text = text


def marker_paragraph(text: str) -> etree._Element:
    paragraph = etree.Element(qn("p"))
    rewrite_paragraph(paragraph, text)
    return paragraph


def strip_direct_highlight(paragraph: etree._Element) -> None:
    nodes = paragraph.xpath(
        "./w:pPr/w:shd | .//w:rPr/w:highlight | .//w:rPr/w:shd",
        namespaces=NS,
    )
    for node in nodes:
        parent = node.getparent()
        if parent is not None:
            parent.remove(node)


def paragraph_style_ids(paragraph: etree._Element) -> set[str]:
    values = paragraph.xpath(
        "./w:pPr/w:pStyle/@w:val | .//w:rPr/w:rStyle/@w:val",
        namespaces=NS,
    )
    return {str(value) for value in values}


def strip_style_highlights(styles_xml: bytes, style_ids: set[str]) -> bytes:
    if not styles_xml or not style_ids:
        return styles_xml

    root = etree.fromstring(styles_xml)
    for style in root.xpath(".//w:style", namespaces=NS):
        if style.get(qn("styleId")) not in style_ids:
            continue
        for node in style.xpath(".//w:rPr/w:highlight | .//w:rPr/w:shd", namespaces=NS):
            parent = node.getparent()
            if parent is not None:
                parent.remove(node)

    return etree.tostring(root, xml_declaration=True, encoding="UTF-8", standalone=True)


def preprocess_docx(source: Path, destination: Path) -> list[str]:
    """Normalize markers, retain blank paragraphs, and expose Word sections."""
    with zipfile.ZipFile(source, "r") as archive:
        entries = {item.filename: archive.read(item.filename) for item in archive.infolist()}

    try:
        root = etree.fromstring(entries["word/document.xml"])
    except KeyError as exc:
        raise ValueError("Input is not a valid DOCX file.") from exc

    body = root.find(f".//{qn('body')}")
    if body is None:
        raise ValueError("DOCX body not found.")

    title_style_ids: set[str] = set()
    native_sections: list[str] = []
    on_title_page = True

    for paragraph in list(body):
        if paragraph.tag != qn("p"):
            continue

        text = norm(paragraph_text(paragraph))
        sect_pr = paragraph.find(f"./{qn('pPr')}/{qn('sectPr')}")
        explicit_section = SECTION_RE.fullmatch(text) is not None

        if on_title_page:
            strip_direct_highlight(paragraph)
            title_style_ids.update(paragraph_style_ids(paragraph))

        if explicit_section:
            rewrite_paragraph(paragraph, "[[DOCX_SECTION:nextPage]]")
            text = "[[DOCX_SECTION:nextPage]]"
        else:
            figure_match = FIGURE_RE.fullmatch(text)
            if figure_match:
                pages = figure_match.group("pages")
                normalized = f"[[PDF_FIGURE: {figure_match.group('name').strip()}"
                if pages:
                    normalized += f"; pages={pages.strip()}"
                rewrite_paragraph(paragraph, normalized + "]]" )
            elif not text and sect_pr is None and not has_nontext_content(paragraph):
                rewrite_paragraph(paragraph, BLANK_MARKER)

        if sect_pr is not None:
            type_node = sect_pr.find(qn("type"))
            kind = type_node.get(qn("val"), "nextPage") if type_node is not None else "nextPage"
            kind = kind or "nextPage"
            next_node = paragraph.getnext()
            next_text = norm(paragraph_text(next_node)) if next_node is not None and next_node.tag == qn("p") else ""
            if not (SECTION_RE.fullmatch(next_text) or INTERNAL_SECTION_RE.fullmatch(next_text)):
                paragraph.addnext(marker_paragraph(f"[[DOCX_SECTION:{kind}]]"))
            native_sections.append(kind)

        if explicit_section or sect_pr is not None:
            on_title_page = False

    entries["word/document.xml"] = etree.tostring(
        root, xml_declaration=True, encoding="UTF-8", standalone=True
    )
    if "word/styles.xml" in entries:
        entries["word/styles.xml"] = strip_style_highlights(
            entries["word/styles.xml"], title_style_ids
        )

    with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED) as archive:
        for name, data in entries.items():
            archive.writestr(name, data)

    return native_sections


def normalize_figure_key(value: str) -> str:
    value = value.strip().strip('"').strip("'").replace("\\", "/")
    value = value.rsplit("/", 1)[-1]
    if value.lower().endswith(".pdf"):
        value = value[:-4]
    return value.casefold()


def index_figures(directory: Path) -> dict[str, Figure]:
    if not directory.is_dir():
        raise FileNotFoundError(f"Figure directory not found: {directory}")

    paths = sorted(
        (p.resolve() for p in directory.iterdir() if p.is_file() and p.suffix.lower() == ".pdf"),
        key=lambda p: p.name.casefold(),
    )
    if not paths:
        raise FileNotFoundError(f"No top-level PDF figures found in: {directory}")

    result: dict[str, Figure] = {}
    for number, path in enumerate(paths, 1):
        key = normalize_figure_key(path.name)
        if key in result:
            raise ValueError(f"Duplicate case-insensitive PDF stem: {path.stem}")
        result[key] = Figure(key, path, f"figure_{number:04d}.pdf", len(PdfReader(str(path)).pages))
    return result


def parse_pages(spec: str | None, page_count: int) -> tuple[int, ...]:
    if not spec or spec.strip().casefold() == "all":
        return tuple(range(1, page_count + 1))

    pages: list[int] = []
    for token in spec.split(","):
        token = token.strip()
        if not token:
            continue
        if "-" in token:
            start, end = (int(value.strip()) for value in token.split("-", 1))
            if start > end:
                raise ValueError(f"Invalid page range: {token}")
            pages.extend(range(start, end + 1))
        else:
            pages.append(int(token))

    pages = list(dict.fromkeys(pages))
    if not pages or any(page < 1 or page > page_count for page in pages):
        raise ValueError(f"Invalid page selection {spec!r} for a {page_count}-page PDF.")
    return tuple(pages)


def inline_text(inlines: list[dict[str, Any]]) -> str:
    parts: list[str] = []
    for inline in inlines:
        kind, content = inline.get("t"), inline.get("c")
        if kind == "Str":
            parts.append(str(content))
        elif kind in {"Space", "SoftBreak", "LineBreak"}:
            parts.append(" ")
        elif kind in {"Code", "Math", "RawInline"} and isinstance(content, list):
            parts.append(str(content[-1]))
        elif kind in {"Emph", "Strong", "Strikeout", "Superscript", "Subscript", "SmallCaps"}:
            parts.append(inline_text(content))
        elif kind in {"Quoted", "Link", "Image", "Span"} and isinstance(content, list):
            nested = content[1] if len(content) > 1 and isinstance(content[1], list) else []
            parts.append(inline_text(nested))
    return "".join(parts)


def block_inlines(block: dict[str, Any]) -> list[dict[str, Any]] | None:
    kind, content = block.get("t"), block.get("c")
    if kind in {"Para", "Plain"} and isinstance(content, list):
        return content
    if kind == "Header" and isinstance(content, list) and len(content) >= 3:
        return content[2] if isinstance(content[2], list) else None
    return None


def block_text(block: dict[str, Any]) -> str | None:
    inlines = block_inlines(block)
    return norm(inline_text(inlines)) if inlines is not None else None


def nested_block_lists(block: dict[str, Any]) -> list[list[dict[str, Any]]]:
    kind, content = block.get("t"), block.get("c")
    if kind == "Div":
        return [content[1]]
    if kind == "BlockQuote":
        return [content]
    if kind == "BulletList":
        return list(content)
    if kind == "OrderedList":
        return list(content[1])
    if kind == "DefinitionList":
        return [definition for _term, definitions in content for definition in definitions]
    return []


def collect_insertions(blocks: list[dict[str, Any]], figures: dict[str, Figure]) -> list[Insertion]:
    result: list[Insertion] = []
    for block in blocks:
        text = block_text(block)
        match = FIGURE_RE.fullmatch(text or "")
        if match:
            key = normalize_figure_key(match.group("name"))
            figure = figures.get(key)
            if figure is None:
                available = ", ".join(item.source.stem for item in figures.values())
                raise FileNotFoundError(f"Figure {match.group('name')!r} not found. Available: {available}")
            result.append(Insertion(text or "", figure, parse_pages(match.group("pages"), figure.page_count)))
            continue
        for nested in nested_block_lists(block):
            result.extend(collect_insertions(nested, figures))
    return result


def strip_ast_highlights(value: Any) -> None:
    """Remove Pandoc background/highlight attributes that survived DOCX parsing."""
    if isinstance(value, dict):
        strip_ast_highlights(value.get("c"))
    elif isinstance(value, list):
        if (
            len(value) == 3
            and isinstance(value[0], str)
            and isinstance(value[1], list)
            and isinstance(value[2], list)
            and all(isinstance(pair, list) and len(pair) == 2 for pair in value[2])
        ):
            value[2][:] = [
                pair for pair in value[2]
                if str(pair[0]).casefold() not in {"background-color", "background", "highlight"}
            ]
        for item in value:
            strip_ast_highlights(item)


def meta_text(meta_value: Any) -> str:
    if not isinstance(meta_value, dict):
        return ""
    kind, content = meta_value.get("t"), meta_value.get("c")
    if kind == "MetaString":
        return norm(str(content))
    if kind == "MetaInlines" and isinstance(content, list):
        return norm(inline_text(content))
    if kind == "MetaBlocks" and isinstance(content, list):
        return norm(" ".join(block_text(block) or "" for block in content))
    return ""


def extract_title(
    document: dict[str, Any],
) -> str:
    """
    Extract the Pandoc title and remove ordinary, non-breaking, and
    zero-width whitespace from its edges.
    """
    meta = document.setdefault("meta", {})

    title = meta_text(
        meta.pop("title", None)
    )

    meta.pop("author", None)
    meta.pop("date", None)

    title = re.sub(
        r"^[\s\u00A0\u2007\u202F\u200B\uFEFF]+",
        "",
        title,
    )
    title = re.sub(
        r"[\s\u00A0\u2007\u202F\u200B\uFEFF]+$",
        "",
        title,
    )

    return title


def latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def figure_latex(
    figure: Figure,
    page: int,
    scale: float,
) -> str:
    """
    Insert a large figure while retaining the normal footer height.

    The fancyhdr footer width is recalculated after each geometry change so
    the page number remains horizontally centered.
    """
    return (
        "\\par\n"
        "\\nolinenumbers\n"
        "\\newgeometry{"
        f"top={FIGURE_TOP_MARGIN_MM:.3f}mm,"
        f"bottom={FIGURE_BOTTOM_MARGIN_MM:.3f}mm,"
        f"left={FIGURE_SIDE_MARGIN_MM:.3f}mm,"
        f"right={FIGURE_SIDE_MARGIN_MM:.3f}mm,"
        f"footskip={FIGURE_FOOTSKIP_MM:.3f}mm"
        "}\n"
        "\\setlength{\\headwidth}{\\textwidth}\n"
        "\\thispagestyle{plain}\n"
        "\\null\\vfill\n"
        "\\noindent\\makebox[\\textwidth][c]{%\n"
        f"  \\includegraphics["
        f"page={page},"
        f"scale={scale:.8f}"
        f"]{{{figure.safe_name}}}%\n"
        "}\n"
        "\\vfill\\null\n"
        "\\restoregeometry\n"
        "\\setlength{\\headwidth}{\\textwidth}\n"
        "\\linenumbers"
    )


def section_latex(kind: str) -> str:
    kind = kind.casefold()
    if kind == "continuous":
        return r"\par"
    if kind == "oddpage":
        page_logic = r"\ifodd\value{page}\else\null\thispagestyle{empty}\newpage\fi"
    elif kind == "evenpage":
        page_logic = r"\ifodd\value{page}\null\thispagestyle{empty}\newpage\fi"
    else:
        page_logic = ""
    return "\\par\n\\nolinenumbers\n\\clearpage\n" + page_logic + "\n\\linenumbers"


def raw_block(latex: str) -> dict[str, Any]:
    return {"t": "RawBlock", "c": ["latex", latex]}


def transform_blocks(
    blocks: list[dict[str, Any]],
    insertion_map: dict[str, Insertion],
    scale: float,
    paragraph_spacing_scope: str,
) -> list[dict[str, Any]]:
    """
    Replace internal markers and switch paragraph spacing at level-1
    manuscript headings.

    paragraph_spacing_scope:
        selective:
            12 pt only in References and Figure Legends sections.
        all:
            12 pt throughout the document.
        none:
            No additional paragraph spacing.
    """
    if paragraph_spacing_scope not in {
        "selective",
        "all",
        "none",
    }:
        raise ValueError(
            "paragraph_spacing_scope must be "
            "'selective', 'all', or 'none'."
        )

    output: list[dict[str, Any]] = []
    skip_blanks = False

    for block in blocks:
        text = block_text(block)

        section_match = INTERNAL_SECTION_RE.fullmatch(
            text or ""
        )
        is_blank = BLANK_RE.fullmatch(
            text or ""
        ) is not None

        if section_match:
            while (
                output
                and output[-1].get("c")
                == ["latex", r"\ManuscriptBlankLine"]
            ):
                output.pop()

            output.append(
                raw_block(
                    section_latex(
                        section_match.group("kind")
                    )
                )
            )
            skip_blanks = True
            continue

        if is_blank:
            if not skip_blanks:
                output.append(
                    raw_block(r"\ManuscriptBlankLine")
                )
            continue

        skip_blanks = False

        figure_match = FIGURE_RE.fullmatch(text or "")

        if figure_match:
            insertion = insertion_map[norm(text or "")]

            for page in insertion.pages:
                output.append(
                    raw_block(
                        figure_latex(
                            insertion.figure,
                            page,
                            scale,
                        )
                    )
                )

            continue

        # Supplementary and extended-data figure captions in the DOCX are
        # Normal paragraphs rather than Pandoc Header blocks. Switch off
        # paragraph spacing when their first paragraph is encountered.
        if (
            paragraph_spacing_scope == "selective"
            and is_figure_legend_start(text)
        ):
            output.append(
                raw_block(
                    r"\ManuscriptParagraphSpacingOff"
                )
            )

        kind = block.get("t")
        content = block.get("c")

        if kind == "Div":
            content[1] = transform_blocks(
                content[1],
                insertion_map,
                scale,
                paragraph_spacing_scope,
            )

        elif kind == "BlockQuote":
            block["c"] = transform_blocks(
                content,
                insertion_map,
                scale,
                paragraph_spacing_scope,
            )

        elif kind == "BulletList":
            block["c"] = [
                transform_blocks(
                    item,
                    insertion_map,
                    scale,
                    paragraph_spacing_scope,
                )
                for item in content
            ]

        elif kind == "OrderedList":
            content[1] = [
                transform_blocks(
                    item,
                    insertion_map,
                    scale,
                    paragraph_spacing_scope,
                )
                for item in content[1]
            ]

        elif kind == "DefinitionList":
            for entry in content:
                entry[1] = [
                    transform_blocks(
                        item,
                        insertion_map,
                        scale,
                        paragraph_spacing_scope,
                    )
                    for item in entry[1]
                ]

        output.append(block)

        # Only level-1 headings switch the active manuscript section.
        # Subheadings within References or Figure Legends do not disable
        # paragraph spacing.
        header = header_level_and_text(block)

        if (
            paragraph_spacing_scope == "selective"
            and header is not None
        ):
            heading_level, heading_text = header

            if section_disables_paragraph_spacing(
                heading_text
            ):
                output.append(
                    raw_block(
                        r"\ManuscriptParagraphSpacingOff"
                    )
                )

            elif heading_level == 1:
                output.append(
                    raw_block(
                        r"\ManuscriptParagraphSpacingOn"
                    )
                )

    return output


def page_size(reader: PdfReader, page_number: int) -> tuple[float, float]:
    page = reader.pages[page_number - 1]
    width, height = float(page.cropbox.width), float(page.cropbox.height)
    if int(page.get("/Rotate", 0) or 0) % 360 in {90, 270}:
        width, height = height, width
    return width, height


def common_scale(
    insertions: list[Insertion],
    paper: str,
    margin_mm: float,
    max_scale: float,
    safety: float,
) -> float:
    """
    Calculate one common scale for all inserted figure pages.

    Figures use narrow top and side margins, but retain the normal manuscript
    bottom margin so the page number stays in its original position.
    """
    paper_width, paper_height = PAPER_SIZES_PT[paper]

    side_margin_pt = FIGURE_SIDE_MARGIN_MM * PT_PER_MM
    top_margin_pt = FIGURE_TOP_MARGIN_MM * PT_PER_MM
    bottom_margin_pt = FIGURE_BOTTOM_MARGIN_MM * PT_PER_MM

    usable_width = paper_width - 2.0 * side_margin_pt
    usable_height = (
        paper_height
        - top_margin_pt
        - bottom_margin_pt
    )

    if usable_width <= 0 or usable_height <= 0:
        raise ValueError(
            "The figure margins leave no usable page area."
        )

    readers: dict[Path, PdfReader] = {}
    limits: list[float] = []

    for insertion in insertions:
        reader = readers.setdefault(
            insertion.figure.source,
            PdfReader(str(insertion.figure.source)),
        )

        for page_number in insertion.pages:
            width, height = page_size(
                reader,
                page_number,
            )

            limits.append(
                min(
                    usable_width / width,
                    usable_height / height,
                )
            )

    if not limits:
        raise ValueError("No figure pages selected.")

    return min(
        max_scale,
        min(limits) * safety,
    )


def latex_header(args: argparse.Namespace) -> str:
    paper_option = (
        "a4paper"
        if args.paper == "a4"
        else "letterpaper"
    )

    font = args.main_font.strip()

    if not font or any(char in font for char in "{}\\\r\n"):
        raise ValueError("Unsafe or empty font name.")

    body_baseline = args.font_size_pt * args.line_spacing
    title_baseline = 12.0 * args.line_spacing

    initial_parskip_pt = (
        0.0
        if args.paragraph_spacing_scope == "none"
        else 12.0
    )

    return rf"""
\usepackage[
  {paper_option},
  top={args.margin_mm:.3f}mm,
  bottom={args.margin_mm:.3f}mm,
  left={args.margin_mm:.3f}mm,
  right={args.margin_mm:.3f}mm
]{{geometry}}

\usepackage{{graphicx}}
\usepackage{{fontspec}}
\usepackage{{fancyhdr}}
\usepackage[left]{{lineno}}
\usepackage{{titlesec}}
\usepackage{{ragged2e}}

\IfFontExistsTF{{{font}}}{{%
  \setmainfont{{{font}}}
  \setsansfont{{{font}}}
}}{{%
  \PackageError{{manuscript-build}}
    {{Required font '{font}' was not found}}
    {{Install the font or use --main-font.}}
}}

% Exact body font size and line spacing.
\makeatletter
\renewcommand{{\normalsize}}{{%
  \@setfontsize\normalsize
    {{{args.font_size_pt:.3f}pt}}
    {{{body_baseline:.3f}pt}}%
}}
\makeatother

% Normal manuscript paragraphs.
\setlength{{\parindent}}{{0pt}}
\setlength{{\JustifyingParindent}}{{0pt}}
\setlength{{\parskip}}{{{initial_parskip_pt:.3f}pt}}

% Section-dependent paragraph spacing.
\newcommand{{\ManuscriptParagraphSpacingOn}}{{%
  \setlength{{\parskip}}{{12pt}}%
}}

\newcommand{{\ManuscriptParagraphSpacingOff}}{{%
  \setlength{{\parskip}}{{0pt}}%
}}

\AtBeginDocument{{%
  \normalsize
  \justifying
  \setlength{{\parindent}}{{0pt}}
  \setlength{{\JustifyingParindent}}{{0pt}}
}}

% Do not create new hyphenation points inside ordinary words.
\hyphenpenalty=10000

% Permit line breaks at hyphens already present in the source text.
\exhyphenpenalty=0

% Avoid several consecutive lines ending with hyphens.
\doublehyphendemerits=10000
\finalhyphendemerits=5000

% Allow enough flexibility to prevent text extending past the margin.
\tolerance=3000
\emergencystretch=6em

% Widow and orphan control.
\clubpenalty=10000
\widowpenalty=10000
\displaywidowpenalty=10000

% Manuscript title:
% Arial 12 pt, bold, left aligned, without leading whitespace.
\newcommand{{\ManuscriptTitle}}[1]{{%
  \begingroup
  \setlength{{\parskip}}{{0pt}}%
  \setlength{{\parindent}}{{0pt}}%
  \raggedright
  \bfseries
  \fontsize{{12pt}}{{{title_baseline:.3f}pt}}%
  \selectfont
  \noindent\ignorespaces#1\unskip\par
  \endgroup
}}

% Preserve actual empty Word paragraphs without applying paragraph spacing
% twice.
\newcommand{{\ManuscriptBlankLine}}{{%
  \par
  \begingroup
  \setlength{{\parskip}}{{0pt}}%
  \noindent
  \mbox{{\strut}}%
  \par
  \endgroup
}}

% Heading level 1.
\titleformat{{\section}}[block]
  {{%
    \normalfont
    \bfseries
    \fontsize
      {{{args.font_size_pt:.3f}pt}}
      {{{body_baseline:.3f}pt}}
    \selectfont
    \raggedright
  }}
  {{}}
  {{0pt}}
  {{}}

\titlespacing*{{\section}}
  {{0pt}}
  {{20pt}}
  {{20pt}}

% Heading level 2.
\titleformat{{\subsection}}[block]
  {{%
    \normalfont
    \bfseries
    \fontsize
      {{{args.font_size_pt:.3f}pt}}
      {{{body_baseline:.3f}pt}}
    \selectfont
    \raggedright
  }}
  {{}}
  {{0pt}}
  {{}}

\titlespacing*{{\subsection}}
  {{0pt}}
  {{12pt}}
  {{12pt}}

% Heading level 3.
\titleformat{{\subsubsection}}[block]
  {{%
    \normalfont
    \bfseries
    \fontsize
      {{{args.font_size_pt:.3f}pt}}
      {{{body_baseline:.3f}pt}}
    \selectfont
    \raggedright
  }}
  {{}}
  {{0pt}}
  {{}}

\titlespacing*{{\subsubsection}}
  {{0pt}}
  {{12pt}}
  {{12pt}}

% Heading level 4.
\titleformat{{\paragraph}}[block]
  {{%
    \normalfont
    \bfseries
    \fontsize
      {{{args.font_size_pt:.3f}pt}}
      {{{body_baseline:.3f}pt}}
    \selectfont
    \raggedright
  }}
  {{}}
  {{0pt}}
  {{}}

\titlespacing*{{\paragraph}}
  {{0pt}}
  {{12pt}}
  {{12pt}}

% Heading level 5.
\titleformat{{\subparagraph}}[block]
  {{%
    \normalfont
    \bfseries
    \fontsize
      {{{args.font_size_pt:.3f}pt}}
      {{{body_baseline:.3f}pt}}
    \selectfont
    \raggedright
  }}
  {{}}
  {{0pt}}
  {{}}

\titlespacing*{{\subparagraph}}
  {{0pt}}
  {{12pt}}
  {{12pt}}

% Page numbering.
\fancyhf{{}}
\fancyfoot[C]{{\thepage}}
\renewcommand{{\headrulewidth}}{{0pt}}
\renewcommand{{\footrulewidth}}{{0pt}}
\pagestyle{{fancy}}

\fancypagestyle{{plain}}{{%
  \fancyhf{{}}
  \fancyfoot[C]{{\thepage}}
  \renewcommand{{\headrulewidth}}{{0pt}}
  \renewcommand{{\footrulewidth}}{{0pt}}
}}

% Continuous line numbering.
\setlength{{\linenumbersep}}{{10pt}}

\renewcommand{{\linenumberfont}}{{%
  \normalfont
  \sffamily
  \fontsize{{8pt}}{{9pt}}
  \selectfont
}}

\AtBeginDocument{{%
  \setcounter{{page}}{{{args.first_page_number}}}
  \setcounter{{linenumber}}{{1}}
  \runninglinenumbers
  \modulolinenumbers[{args.line_number_step}]
}}
""".strip() + "\n"


def convert_docx(pandoc: str, source: Path, media_dir: Path) -> dict[str, Any]:
    return json.loads(
        run(
            [pandoc, str(source), "--from=docx", "--to=json", f"--extract-media={media_dir}"],
            capture=True,
        )
    )


def assert_no_markers(text: str) -> None:
    for marker in ("[[SECTION_BREAK]]", "[[DOCX_SECTION:", "[[DOCX_BLANK]]", "[[PDF_FIGURE:"):
        if marker.casefold() in text.casefold():
            raise RuntimeError(f"Unresolved marker remained in generated LaTeX: {marker}")


def normalized_font_key(name: str) -> str:
    name = re.sub(r"^[A-Z]{6}\+", "", name).casefold()
    return re.sub(r"[^a-z0-9]+", "", name)


def validate_pdf_output(pdf_path: Path, font: str, body_size: float) -> None:
    """Reject stale or incorrectly formatted output instead of silently copying it."""
    reader = PdfReader(str(pdf_path))
    all_text = "\n".join(page.extract_text() or "" for page in reader.pages)
    assert_no_markers(all_text)

    page_index = next(
        (i for i, page in enumerate(reader.pages) if len(norm(page.extract_text() or "")) >= 200),
        None,
    )
    if page_index is None:
        raise RuntimeError("Could not find a substantial text page for PDF validation.")

    page = reader.pages[page_index]
    resources = page.get("/Resources")
    fonts = resources.get_object().get("/Font") if resources is not None else None
    font_names: list[str] = []
    if fonts is not None:
        for reference in fonts.get_object().values():
            font_dict = reference.get_object()
            base_font = font_dict.get("/BaseFont")
            if base_font is not None:
                font_names.append(str(base_font).lstrip("/"))
            descendants = font_dict.get("/DescendantFonts")
            if descendants is not None:
                for descendant in descendants:
                    descendant_name = descendant.get_object().get("/BaseFont")
                    if descendant_name is not None:
                        font_names.append(str(descendant_name).lstrip("/"))

    requested = normalized_font_key(font)
    if not any(requested in normalized_font_key(name) for name in font_names):
        raise RuntimeError(
            f"Generated PDF does not use {font!r} on text page {page_index + 1}. "
            f"Detected fonts: {sorted(set(font_names))}"
        )

    sizes: list[float] = []
    contents = page.get_contents()
    if contents is not None:
        for operands, operator in ContentStream(contents, reader).operations:
            if operator == b"Tf" and len(operands) >= 2:
                try:
                    sizes.append(float(operands[1]))
                except (TypeError, ValueError):
                    pass

    def has_size(target: float) -> bool:
        return any(abs(value - target) <= 0.3 for value in sizes)

    if not has_size(body_size):
        raise RuntimeError(
            f"Generated PDF does not contain {body_size:g} pt body text on "
            f"page {page_index + 1}. Detected sizes: "
            f"{sorted(set(round(value, 3) for value in sizes))}"
        )
    if not has_size(8.0):
        raise RuntimeError(
            "Generated PDF does not contain the expected 8 pt line numbers. "
            f"Detected sizes: {sorted(set(round(value, 3) for value in sizes))}"
        )


def save_debug(temp_dir: Path, debug_dir: Path, enabled: bool) -> None:
    if not enabled:
        return
    try:
        if debug_dir.exists():
            shutil.rmtree(debug_dir)
        shutil.copytree(temp_dir, debug_dir)
    except Exception as exc:
        print(f"Warning: could not save intermediate files: {exc}", file=sys.stderr)


def build(args: argparse.Namespace) -> None:
    source = args.source.resolve()
    output = args.output.resolve()
    figures_dir = args.figures_dir.resolve() if args.figures_dir else source.parent / "figures"

    if not source.is_file() or source.suffix.lower() != ".docx":
        raise FileNotFoundError(f"DOCX source not found: {source}")
    if output.suffix.lower() != ".pdf":
        raise ValueError("Output must use the .pdf extension.")
    if args.margin_mm <= 0 or args.font_size_pt <= 0 or args.line_spacing <= 0:
        raise ValueError("Margins, font size, and line spacing must be positive.")
    if args.line_number_step < 1 or args.first_page_number < 1:
        raise ValueError("Line-number step and first page number must be at least 1.")
    if not 0 < args.fit_safety <= 1 or args.max_scale <= 0:
        raise ValueError("Invalid figure scale settings.")

    pandoc = require_program(args.pandoc)
    xelatex = require_program(args.pdf_engine)
    figures = index_figures(figures_dir)
    output.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="docx_pdf_") as temp_name:
        temp_dir = Path(temp_name)
        prepared = temp_dir / "prepared.docx"
        media_dir = temp_dir / "media"
        ast_path = temp_dir / "document.json"
        header_path = temp_dir / "header.tex"
        tex_path = temp_dir / "manuscript.tex"
        debug_dir = output.parent / f"{output.stem}_build_files"

        try:
            native_sections = preprocess_docx(source, prepared)
            document = convert_docx(pandoc, prepared, media_dir)
            strip_ast_highlights(document)
            title = extract_title(document)

            blocks = document.get("blocks")
            if not isinstance(blocks, list):
                raise ValueError("Pandoc returned invalid document blocks.")

            prepared_texts = [block_text(block) or "" for block in blocks]
            section_count = sum(
                INTERNAL_SECTION_RE.fullmatch(text) is not None
                for text in prepared_texts
            )
            blank_count = sum(
                BLANK_RE.fullmatch(text) is not None
                for text in prepared_texts
            )

            insertions = collect_insertions(blocks, figures)
            if not insertions:
                raise ValueError("No [[PDF_FIGURE: ...]] markers found.")

            scale = common_scale(
                insertions, args.paper, args.margin_mm, args.max_scale, args.fit_safety
            )
            insertion_map = {norm(item.raw_marker): item for item in insertions}
            processed = transform_blocks(
                blocks,
                insertion_map,
                scale,
                args.paragraph_spacing_scope,
            )

            prefix = [raw_block(r"\linenumbers")]
            if title:
                prefix.append(raw_block(r"\ManuscriptTitle{" + latex_escape(title) + "}"))
            document["blocks"] = prefix + processed

            copied: set[Path] = set()
            for insertion in insertions:
                if insertion.figure.source not in copied:
                    shutil.copy2(insertion.figure.source, temp_dir / insertion.figure.safe_name)
                    copied.add(insertion.figure.source)

            ast_path.write_text(json.dumps(document, ensure_ascii=False), encoding="utf-8")
            header_path.write_text(latex_header(args), encoding="utf-8")

            resources = os.pathsep.join([str(temp_dir), str(media_dir), str(source.parent)])
            run(
                [
                    pandoc,
                    str(ast_path),
                    "--from=json",
                    "--to=latex",
                    "--standalone",
                    "--pdf-engine=xelatex",
                    "--variable", "documentclass=article",
                    "--variable", f"classoption={args.font_size_pt:g}pt",
                    "--variable", f"fontsize={args.font_size_pt:g}pt",
                    "--variable", f"mainfont={args.main_font}",
                    "--include-in-header", str(header_path),
                    "--resource-path", resources,
                    "--output", str(tex_path),
                ],
                cwd=temp_dir,
            )

            latex_text = tex_path.read_text(
                encoding="utf-8",
            )

            latex_text = normalize_unicode_scripts_in_latex(
                latex_text
            )

            tex_path.write_text(
                latex_text,
                encoding="utf-8",
            )

            assert_no_markers(latex_text)

            command = [
                xelatex,
                "-interaction=nonstopmode",
                "-halt-on-error",
                "-file-line-error",
                tex_path.name,
            ]
            run(command, cwd=temp_dir)
            run(command, cwd=temp_dir)

            built_pdf = tex_path.with_suffix(".pdf")
            if not built_pdf.is_file():
                raise RuntimeError("XeLaTeX did not produce a PDF.")

            validate_pdf_output(
                built_pdf,
                font=args.main_font,
                body_size=args.font_size_pt,
            )
            shutil.copy2(built_pdf, output)

            print(f"Script version: {SCRIPT_VERSION}")
            print(f"Source DOCX: {source}")
            print(f"Figure directory: {figures_dir}")
            print(f"Indexed PDF figures: {len(figures)}")
            print(f"Figure markers found: {len(insertions)}")
            print(f"Native Word section breaks found: {len(native_sections)}")
            print(f"Total section markers prepared: {section_count}")
            print(f"Blank paragraphs prepared: {blank_count}")
            print(f"Common figure scale: {scale:.6f}")
            print(f"Formatting: {args.main_font}, {args.font_size_pt:g} pt, {args.line_spacing:g}-line spacing")
            print(f"Output PDF: {output}")
        finally:
            save_debug(temp_dir, debug_dir, args.keep_intermediate)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert DOCX to PDF, preserve section/blank markers, and insert vector PDF figures."
    )
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--figures-dir", type=Path)
    parser.add_argument("--paper", choices=sorted(PAPER_SIZES_PT), default="a4")
    parser.add_argument("--margin-mm", type=float, default=25.4)
    parser.add_argument("--main-font", default="Arial")
    parser.add_argument("--font-size-pt", type=float, default=11.0)
    parser.add_argument("--line-spacing", type=float, default=1.5)
    parser.add_argument("--line-number-step", type=int, default=1)
    parser.add_argument("--max-scale", type=float, default=0.95)
    parser.add_argument("--fit-safety", type=float, default=0.985)
    parser.add_argument("--first-page-number", type=int, default=1)
    parser.add_argument("--pdf-engine", default="xelatex")
    parser.add_argument("--pandoc", default="pandoc")
    parser.add_argument("--keep-intermediate", action="store_true")
    parser.add_argument(
        "--paragraph-spacing-scope",
        choices=("selective", "all", "none"),
        default="selective",
        help=(
            "Where to apply 12 pt spacing after paragraphs. "
            "'selective' applies it only in References and "
            "Figure Legends sections; 'all' applies it throughout "
            "the document; 'none' disables it. "
            "Default: selective."
        ),
    )
    return parser.parse_args()


def main() -> int:
    try:
        build(parse_args())
    except subprocess.CalledProcessError as exc:
        print(f"Build command failed with exit code {exc.returncode}.", file=sys.stderr)
        return exc.returncode or 1
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

